#!/bin/bash

echo "🚀 CONFIGURACIÓN RÁPIDA DE SUPABASE"
echo ""
echo "📋 Este script te guiará paso a paso:"
echo ""
echo "1️⃣ PASO 1: Crear cuenta en Supabase"
echo "   - Ve a: https://supabase.com"
echo "   - Haz clic en 'Start your project'"
echo "   - Crea cuenta gratuita (sin tarjeta)"
echo ""
echo "2️⃣ PASO 2: Crear proyecto"
echo "   - Haz clic en 'New Project'"
echo "   - Nombre: temporizador-juegos"
echo "   - Contraseña: [elige una segura]"
echo "   - Región: [la más cercana]"
echo "   - Clic en 'Create new project'"
echo ""
echo "3️⃣ PASO 3: Obtener connection string"
echo "   - Ve a Settings → Database"
echo "   - Connection string → Copia la URL"
echo "   - Debería verse como:"
echo "     postgresql://postgres:[password]@db.[project].supabase.co:5432/postgres"
echo ""
echo "4️⃣ PASO 4: Configurar variable de entorno"
echo "   - Ejecuta: export DATABASE_URL='[tu connection string]'"
echo "   - O configúrala en Vercel: Settings → Environment Variables"
echo ""
echo "5️⃣ PASO 5: Probar conexión"
echo "   - Ejecuta: node test-supabase.js"
echo ""
echo "6️⃣ PASO 6: Migrar datos"
echo "   - Ejecuta: node migrate-to-postgres.js"
echo ""
echo "✅ ¡LISTO! Tendrás persistencia real y gratuita"
echo ""
echo "🔗 Enlaces:"
echo "   - Supabase: https://supabase.com"
echo "   - Tu proyecto: Se genera automáticamente"
echo ""
