// Script para configurar Neon automáticamente
console.log('🚀 Configuración de Neon (PostgreSQL GRATUITO)');
console.log('');
console.log('📋 PASOS PARA CONFIGURAR:');
console.log('');
console.log('1️⃣ Ve a https://neon.tech');
console.log('2️⃣ Crea una cuenta gratuita (sin tarjeta de crédito)');
console.log('3️⃣ Crea un nuevo proyecto');
console.log('4️⃣ Copia la connection string que aparece');
console.log('5️⃣ Ve a tu proyecto en Vercel');
console.log('6️⃣ Settings → Environment Variables');
console.log('7️⃣ Agrega: DATABASE_URL = [tu connection string]');
console.log('8️⃣ Redespliega la aplicación');
console.log('');
console.log('✅ BENEFICIOS:');
console.log('- 100% GRATUITO para siempre');
console.log('- 3GB de almacenamiento gratuito');
console.log('- Sin límites de tiempo');
console.log('- Persistencia real en la nube');
console.log('- Datos nunca se pierden');
console.log('');
console.log('🔧 ALTERNATIVA: Supabase');
console.log('1️⃣ Ve a https://supabase.com');
console.log('2️⃣ Crea una cuenta gratuita');
console.log('3️⃣ Crea un nuevo proyecto');
console.log('4️⃣ Settings → Database → Connection string');
console.log('5️⃣ Usa la misma variable DATABASE_URL');
console.log('');
console.log('📚 Más información en: database-config.md');
